# Should only server operators be allowed to change settings on the signs?
op-change-settings: false
# How many rounds should a team have to win to win the entire game? Note win by 2 rule will still add rounds after this
round-win-limit: 3
# Should a team have to win by two rounds in order to win the game? i.e. if score is 2-2, a team must get 4 round wins, 3-3, a team must get 5 round wins etc.
win-by-2: true
# Should we play pigstep if we have a 1v1?
one-vs-one-pigstep: true
# Where is the arena located at? Set this using /dodgebolt setlocation
arena-location:
